name: Deploy ONNX to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Who am I?
      run: gcloud auth list

    - name: Build and Push Docker Image
      run: |
        gcloud builds submit \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --tag asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-repo/iris-predict

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy iris-predict \
          --image asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-repo/iris-predict \
          --region asia-southeast1 \
          --platform managed \
          --allow-unauthenticated

